package com.whispereverywhere.npu

/**
 * The whisper-small vocabulary's special ids, its 99-language table, and the two suppression sets
 * from `generation_config.json`.
 *
 * These are **asset facts**. The NPU tier drives a precompiled QAIRT graph whose output layer is
 * `[1, 51865, 1, 1]`; every number in this file describes a slot in that layer. Get one wrong and
 * nothing fails — the decoder emits a different token, the detokeniser renders it, and the user
 * reads a fluent sentence that is not what they said. That is why the constants live in one named
 * place with the assertions in `NpuDecodePolicyTest` rather than spread across the code that uses
 * them.
 *
 * PROVENANCE.
 *  - Special ids and `MAX_POSITIONS`: the 4.0 plan's asset block, read out of the shipped
 *    `metadata.json` and `openai/whisper-small`'s tokenizer. `MAX_POSITIONS` is **200 because the
 *    asset's `attention_mask` is `[1,1,1,200]`** — whisper's own `max_length` of 448 is unreachable
 *    on this graph and is not the number to use.
 *  - [LANGUAGE_CODES]: whisper's canonical language order, index 0..98. Taken from the vendored
 *    `app/src/main/cpp/whisper.cpp/src/whisper.cpp` `g_lang` table (indices 0..98; its index 99
 *    `yue` is large-v3-only and has no id in this 51,865-entry vocabulary), which is the same
 *    ordering `openai/whisper-small`'s `added_tokens.json` assigns ids in. Cross-checked against
 *    the four ids the plan quotes independently: `<|en|>` 50259, `<|zh|>` 50260, `<|de|>` 50261,
 *    `<|es|>` 50262, `<|fr|>` 50265 — all four land where `50259 + index` puts them.
 *  - [SUPPRESS] / [BEGIN_SUPPRESS]: `openai/whisper-small`'s `generation_config.json`, verbatim.
 *
 * The table is generated by the `50259 + index` rule rather than written out as 99 pairs, and it is
 * **bidirectional**. Both of those are requirements, not conveniences: a partial table with an
 * English fallback passes every test that spot-checks the common five while transcribing an
 * explicitly-selected Slovenian user as English, and Q6's detect pass returns an *id* that a diag
 * line has to be able to name.
 */
object WhisperTokens {

    // ---------------------------------------------------------------- special ids

    /** `<|endoftext|>` — the decode loop's terminator, and the only one short of the position cap. */
    const val EOT = 50257

    /** `<|startoftranscript|>` — prompt token 0, and the input to the language-detect pass. */
    const val SOT = 50258

    /** `<|translate|>`. Named so it can be asserted ABSENT; this tier never translates. */
    const val TRANSLATE = 50358

    /** `<|transcribe|>` — prompt token 2. One above [TRANSLATE], which is why both are named here. */
    const val TRANSCRIBE = 50359

    /** `<|notimestamps|>` — prompt token 3, and the reason timestamps are a decode fault. */
    const val NO_TIMESTAMPS = 50363

    /** `<|0.00|>`. Every id from here to [VOCAB]`- 1` is a timestamp: 1501 of them. */
    const val TIMESTAMP_BEGIN = 50364

    /**
     * 51,865 — the decoder's `logits` dimension. **Not** 51,866, which is large-v3/turbo.
     *
     * Native derives its argmax bound from the logits tensor itself rather than from this constant,
     * so the two are independent readings of the same asset fact and a disagreement is visible.
     */
    const val VOCAB = 51865

    /**
     * 200 — from the asset's `attention_mask [1,1,1,200]` and its 199-deep self-KV, **not** from
     * whisper's `max_length` of 448, which this graph cannot reach.
     *
     * Positions 0..198 execute (199 of them, an exact fit for the 199 cache slots) and use 199 of
     * the mask's 200 columns; 199 is the termination threshold, not an executing position.
     */
    const val MAX_POSITIONS = 200

    /** `<|en|>`, the first language token. */
    const val LANG_FIRST = 50259

    /** `<|su|>`, the last. [LANG_FIRST]` + 98`. */
    const val LANG_LAST = LANG_FIRST + 98

    // ---------------------------------------------------------------- the language table

    /**
     * Whisper's 99 language codes **in id order**: `langToken(LANGUAGE_CODES[i]) == 50259 + i`.
     *
     * The order is load-bearing and is not alphabetical, not by speaker count, and not stable under
     * "tidying". It is the order whisper's own tokenizer appended the tokens in, which is the order
     * the model's embedding rows are in.
     */
    val LANGUAGE_CODES: List<String> = listOf(
        "en", "zh", "de", "es", "ru", "ko", "fr", "ja", "pt", "tr",
        "pl", "ca", "nl", "ar", "sv", "it", "id", "hi", "fi", "vi",
        "he", "uk", "el", "ms", "cs", "ro", "da", "hu", "ta", "no",
        "th", "ur", "hr", "bg", "lt", "la", "mi", "ml", "cy", "sk",
        "te", "fa", "lv", "bn", "sr", "az", "sl", "kn", "et", "mk",
        "br", "eu", "is", "hy", "ne", "mn", "bs", "kk", "sq", "sw",
        "gl", "mr", "pa", "si", "km", "sn", "yo", "so", "af", "oc",
        "ka", "be", "tg", "sd", "gu", "am", "yi", "lo", "uz", "fo",
        "ht", "ps", "tk", "nn", "mt", "sa", "lb", "my", "bo", "tl",
        "mg", "as", "tt", "haw", "ln", "ha", "ba", "jw", "su"
    )

    private val tokenByCode: Map<String, Int> =
        LANGUAGE_CODES.withIndex().associate { (index, code) -> code to LANG_FIRST + index }

    /**
     * The `<|xx|>` token id for a whisper language code.
     *
     * **Throws on an unknown code, and that is the whole point.** Returning [SOT]`+ 1` or falling
     * back to English would make an unsupported locale indistinguishable from an English one at
     * every layer above this, and the symptom is a fluent transcript in the wrong language. Callers
     * that legitimately do not know the language must run `nativeDetectLanguage` instead of guessing
     * here; `"auto"` is not a whisper code and is refused like any other.
     */
    fun langToken(code: String): Int = tokenByCode[code] ?: throw IllegalArgumentException(
        "'$code' is not one of whisper's ${LANGUAGE_CODES.size} language codes. It cannot be " +
            "mapped to a <|lang|> token, and falling back to English here would produce a fluent " +
            "transcript in the wrong language rather than an error."
    )

    /**
     * The whisper language code for a `<|xx|>` token id, or `null` for anything outside
     * [LANG_FIRST]`..`[LANG_LAST].
     *
     * The `null` is the gate on Q6's detect pass: a decoder that argmaxed to `<|transcribe|>` or a
     * timestamp must not be able to smuggle that id through as a "detected language".
     */
    fun codeForToken(id: Int): String? =
        if (id in LANG_FIRST..LANG_LAST) LANGUAGE_CODES[id - LANG_FIRST] else null

    // ---------------------------------------------------------------- the suppression sets

    /**
     * `generation_config.json`'s `suppress_tokens` — 88 ids, verbatim, ascending.
     *
     * These are whisper's non-speech tokens (punctuation runs, musical notation, bracketed sound
     * annotations) plus the control tokens the model must never emit mid-transcript: 50258 (SOT),
     * 50358..50362 (translate, transcribe, startoflm, startofprev, nospeech).
     *
     * **50257 (EOT) is deliberately absent.** It belongs in [BEGIN_SUPPRESS], which applies at one
     * step; suppressing it at every step would remove the loop's only terminator.
     */
    val SUPPRESS: IntArray = intArrayOf(
        1, 2, 7, 8, 9, 10, 14, 25, 26, 27,
        28, 29, 31, 58, 59, 60, 61, 62, 63, 90,
        91, 92, 93, 359, 503, 522, 542, 873, 893, 902,
        918, 922, 931, 1350, 1853, 1982, 2460, 2627, 3246, 3253,
        3268, 3536, 3846, 3961, 4183, 4667, 6585, 6647, 7273, 9061,
        9383, 10428, 10929, 11938, 12033, 12331, 12562, 13793, 14157, 14635,
        15265, 15618, 16553, 16604, 18362, 18956, 20075, 21675, 22520, 26130,
        26161, 26435, 28279, 29464, 31650, 32302, 32470, 36865, 42863, 47425,
        49870, 50254, 50258, 50358, 50359, 50360, 50361, 50362
    )

    /**
     * `generation_config.json`'s `begin_suppress_tokens` — applied at the **first generated step
     * only** (`position == promptLen - 1`), never at `position == 0`.
     *
     * 220 is the leading-space token: a transcript must not open with a space. 50257 is EOT: the
     * model must not decline to say anything at all before it has said anything at all.
     */
    val BEGIN_SUPPRESS: IntArray = intArrayOf(220, EOT)

    // ---------------------------------------------------------------- the family (4.1 L2)

    /**
     * The **82 base BPE ids** of [SUPPRESS] — every entry below [EOT] — transcribed AGAIN, as its
     * own literal array, and that repetition is the design rather than an oversight.
     *
     * [WhisperTokenFamily.suppress] is `BASE_SUPPRESS` plus the six control ids it derives from
     * `langCount`, which is what lets one derivation serve two vocabularies whose specials sit one
     * id apart. If that derivation read [SUPPRESS] and filtered it, `WhisperTokenFamilyTest`'s
     * element-for-element comparison against [SUPPRESS] would be comparing a list with itself —
     * green under every transcription error either copy could contain. Two literal readings, one
     * comparison between them: the same discipline as native's `kEotToken` beside Kotlin's [EOT].
     *
     * The split point is `< EOT` and it is not arbitrary: everything at or above [EOT] in
     * `generation_config.json`'s list is a control token whose id MOVES with the language table
     * ([SOT] is the one exception — it sits below the table — and it is derived with the other five
     * because it is a control token by kind, which is what the derivation is about).
     *
     * **Measured, not assumed**, at plan time: this half is byte-identical between
     * `openai/whisper-small` and `large-v3-turbo`. Only the six above it shift.
     */
    val BASE_SUPPRESS: IntArray = intArrayOf(
        1, 2, 7, 8, 9, 10, 14, 25, 26, 27,
        28, 29, 31, 58, 59, 60, 61, 62, 63, 90,
        91, 92, 93, 359, 503, 522, 542, 873, 893, 902,
        918, 922, 931, 1350, 1853, 1982, 2460, 2627, 3246, 3253,
        3268, 3536, 3846, 3961, 4183, 4667, 6585, 6647, 7273, 9061,
        9383, 10428, 10929, 11938, 12033, 12331, 12562, 13793, 14157, 14635,
        15265, 15618, 16553, 16604, 18362, 18956, 20075, 21675, 22520, 26130,
        26161, 26435, 28279, 29464, 31650, 32302, 32470, 36865, 42863, 47425,
        49870, 50254
    )

    /**
     * **The `npu` tier's token family** — `whisper-small`'s 99 languages and 200-position context,
     * derived rather than transcribed (4.1 L2).
     *
     * Everything above is a literal read off the asset; this is the same asset read a second time
     * through [WhisperTokenFamily]'s formula, and `WhisperTokenFamilyTest` compares the two id by
     * id, code by code and entry by entry. Neither is the "real" one: a disagreement means one of
     * the two readings is wrong and says so, which is the only property that survives a second
     * vocabulary arriving (4.1 L4).
     *
     * It lives here rather than on [WhisperTokenFamily] because this object is already the app's
     * one answer to *"what are whisper-small's token ids"*, and a second home for that answer is a
     * second thing that can drift.
     */
    val SMALL: WhisperTokenFamily = WhisperTokenFamily(langCount = 99, maxPositions = MAX_POSITIONS)

    /**
     * **The `npu-turbo` tier's token family** — `large-v3`'s 100 languages in the same 200-position
     * context (4.1 L4).
     *
     * `langCount = 100` is the WHOLE difference from [SMALL], and it moves seven ids: the band
     * grows to `50259..50358` (`<|yue|>` lands on the id [SMALL] uses for `<|translate|>`) and
     * every control token above it shifts up by one, ending at a 51,866-wide logits layer. See the
     * hazard table in [WhisperTokenFamily]'s KDoc — no per-id check can tell the two layouts apart,
     * which is why this handle exists as a value to THREAD rather than a set of constants to copy.
     *
     * Unlike [SMALL] there is no literal table above it to compare against: this object is
     * `whisper-small`'s reading and carries no large-v3 literals. The second, independent reading
     * for THIS family is the shipped asset itself — `whisper_vocab_turbo.json` — and
     * `TurboVocabAssetTest` is the comparison: every special id the derivation claims is asserted
     * against the token string at that index in the file the APK actually carries.
     *
     * `maxPositions` is [MAX_POSITIONS] because turbo's own `metadata.json` carries the identical
     * `attention_mask [1,1,1,200]` and 199-deep self-KV (measured at plan time, and re-checked by
     * the census guard at load) — the same shift register, not an assumption of sameness.
     */
    val LARGE_V3: WhisperTokenFamily =
        WhisperTokenFamily(langCount = 100, maxPositions = MAX_POSITIONS)
}
