"""The cross-trace fixture THE BACKPRESSURE GOVERNOR's two implementations replay (build 85).

`tests/fixtures/backpressure_cross_trace.csv` is generated by `write()` below (run this module
to regenerate it) and read by BOTH
`test_backpressure.py::test_the_cross_trace_fixture_replays_to_its_own_expectations` and
`SileroEndpointerBackpressureTest.the_cross_trace_fixture_commits_where_the_simulator_says`.

One row per frame: `i,p,depth` — `depth` is the segment-queue depth to publish BEFORE frame `i`
(`on_queue_depth` / `onQueueDepth`), blank when nothing is published on that frame. The header
carries the two floors, the base clock and the EXPECTED commit instants and mode steps: the
simulator's own output, which the Kotlin must reproduce frame for frame. The Python test also
asserts that the file on disk is exactly what `render()` produces today, so the fixture cannot
rot silently when either the trace or the machine changes — regenerate it, and the Kotlin side
re-reads the new expectations on its next run.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Sequence, Tuple

from vadsim.machine import BASE_MS, FRAME_MS, SileroEndpointerSim, Transition, Tuning

FIXTURE = Path(__file__).parent / "fixtures" / "backpressure_cross_trace.csv"

#: turbo's two rows — CommitCadencePolicy.MIN_COMMIT_INTERVAL_TURBO_MS / _TURBO_SLOW_MS
FAST_MS = 2_000
SLOW_MS = 3_200

#: frame index -> depth published BEFORE that frame. Deliberately OFF the utterance grid (the
#: endpoints land at 31 + 23k), so every change is mid-interval and takes effect at the next
#: endpoint; the walk 0 -> 2 -> 1 -> 3 -> 0 -> 2 -> 1 -> 0 crosses both edges several times and
#: includes a "deeper is not a transition" step (1 -> 3 is an enter, 3 -> 0 a leave).
SCHEDULE: Dict[int, int] = {101: 2, 403: 1, 705: 3, 1007: 0, 1309: 2, 1611: 1, 1913: 0}


def build_trace(utterances: int = 120) -> List[float]:
    """The free first cut (20 speech frames + the hangover), then `utterances` on the 736 ms
    grid — SPEECH_FRAMES_OVER_MIN of speech and HANGOVER_FRAMES of silence each."""
    t = Tuning()
    probs: List[float] = [0.9] * 20 + [0.1] * t.hangover_frames()
    for _ in range(utterances):
        probs += [0.9] * t.speech_frames_over_min() + [0.1] * t.hangover_frames()
    return probs


def replay(
    probs: Sequence[float],
    schedule: Dict[int, int],
    fast_ms: int = FAST_MS,
    slow_ms: int = SLOW_MS,
) -> Tuple[List[int], List[Transition]]:
    """Drive a bare endpointer the way the Kotlin test drives `SileroEndpointer`: publish the
    scheduled depth before the frame, then feed the frame at `BASE_MS + i * FRAME_MS`."""
    ep = SileroEndpointerSim(Tuning())
    ep.on_session_start(now_ms=BASE_MS, min_commit_interval_ms=fast_ms, slow_commit_interval_ms=slow_ms)
    commits: List[int] = []
    for i, p in enumerate(probs):
        if i in schedule:
            ep.on_queue_depth(schedule[i])
        t_ms = BASE_MS + i * FRAME_MS
        if ep.on_frame(p, t_ms):
            commits.append(t_ms)
    return commits, list(ep.transitions)


def render(probs: Sequence[float], schedule: Dict[int, int]) -> str:
    commits, transitions = replay(probs, schedule)
    lines = [
        "# vadsim backpressure cross-trace fixture - generated by tests/backpressure_fixture.py; do not hand-edit",
        f"# base_ms={BASE_MS} frame_ms={FRAME_MS} fast_ms={FAST_MS} slow_ms={SLOW_MS}",
        "# expect_commits=" + ",".join(str(c) for c in commits),
        "# expect_transitions=" + ",".join(
            f"{'slow' if tr.slow else 'fast'}@{tr.t_ms}" for tr in transitions
        ),
        "i,p,depth",
    ]
    for i, p in enumerate(probs):
        depth = "" if i not in schedule else str(schedule[i])
        lines.append(f"{i},{p:.2f},{depth}")
    return "\n".join(lines) + "\n"


def parse(text: str) -> Tuple[dict, List[float], Dict[int, int]]:
    """The reader both suites implement: header `key=value` pairs, then `i,p,depth` rows."""
    header: dict = {}
    probs: List[float] = []
    schedule: Dict[int, int] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            body = line[1:].strip()
            if "=" in body and " " not in body.split("=", 1)[0]:
                for token in body.split():
                    if "=" in token:
                        k, v = token.split("=", 1)
                        header[k] = v
            continue
        if line == "i,p,depth":
            continue
        i_s, p_s, d_s = line.split(",")
        i = int(i_s)
        assert i == len(probs), f"fixture rows must be dense: expected {len(probs)}, got {i}"
        probs.append(float(p_s))
        if d_s != "":
            schedule[i] = int(d_s)
    return header, probs, schedule


def expected_commits(header: dict) -> List[int]:
    raw = header.get("expect_commits", "")
    return [int(x) for x in raw.split(",") if x]


def expected_transitions(header: dict) -> List[Tuple[str, int]]:
    raw = header.get("expect_transitions", "")
    out: List[Tuple[str, int]] = []
    for token in raw.split(","):
        if token:
            mode, t = token.split("@")
            out.append((mode, int(t)))
    return out


def write(path: Path = FIXTURE) -> str:
    text = render(build_trace(), SCHEDULE)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return text


if __name__ == "__main__":
    written = write()
    print(f"wrote {FIXTURE} ({written.count(chr(10))} lines)")
